feat: adding test job

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -264,11 +264,20 @@ jobs:
         with:
           name: submodule_name
       
-      # TODO: Should add check in case submodule_name is null
       - name: Set SUBMODULE_NAME env var
         run: | 
-          echo ::set-env name=SUBMODULE_NAME::$(cat submodule_name/submodule_name.txt)
-          echo SUBMODULE_NAME: $(cat submodule_name/submodule_name.txt)
+#          echo ::set-env name=SUBMODULE_NAME::$(cat submodule_name/submodule_name.txt)
+#          echo SUBMODULE_NAME: $(cat submodule_name/submodule_name.txt)
+          
+          SUB_NAME=$(cat submodule_name/submodule_name.txt)
+
+          if [ -z "$SUB_NAME" ]; then
+            echo "Error: Could not determine submodule name from artifact"
+            exit 1
+          else
+            echo ::set-env name=SUBMODULE_NAME::$SUB_NAME
+            echo SUBMODULE_NAME: $SUB_NAME
+          fi
 
 #       - name: Setup node
 #         if: env.SUBMODULE_NAME != ''
@@ -291,6 +300,66 @@ jobs:
         with:
 #           files: ./${{ env.SUBMODULE_NAME }}/nerdlets/
           path: ${{ env.SUBMODULE_NAME }}
+
+  test:
+    name: test
+    needs: checkout-and-build
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+        
+      # Checkout submodules
+      # Note: Uses 8 jobs for checking out submodules quicker
+      - name: Checkout submodules
+        shell: bash
+        run: |
+          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
+          git config --global url."https://github.com/".insteadOf "git@github.com:"
+          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
+          git submodule sync --recursive
+          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1 --recursive --jobs 8
+          
+      - name: Download submodule_name artifact
+        uses: actions/download-artifact@v1
+        with:
+          name: submodule_name
+      
+      - name: Set SUBMODULE_NAME env var
+        run: | 
+#          echo ::set-env name=SUBMODULE_NAME::$(cat submodule_name/submodule_name.txt)
+#          echo SUBMODULE_NAME: $(cat submodule_name/submodule_name.txt)
+          
+          SUB_NAME=$(cat submodule_name/submodule_name.txt)
+
+          if [ -z "$SUB_NAME" ]; then
+            echo "Error: Could not determine submodule name from artifact"
+            exit 1
+          else
+            echo ::set-env name=SUBMODULE_NAME::$SUB_NAME
+            echo SUBMODULE_NAME: $SUB_NAME
+          fi          
+
+      # TODO: Convert these steps to docker-based action
+      - name: Setup node
+        if: env.SUBMODULE_NAME != ''
+        uses: actions/setup-node@v1
+        with:
+          node-version: "10.x"
+        
+      - name: Install Dependencies
+        if: env.SUBMODULE_NAME != ''
+        working-directory: ./${{ env.SUBMODULE_NAME }}
+        run: npm install
+        
+      - name: Run npm test
+        if: env.SUBMODULE_NAME != ''
+        working-directory: ./${{ env.SUBMODULE_NAME }}
+        run: npm test
 
   publish: 
     name: Publish Nerdpack
