feat: add job to test map-global-uuid action

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -511,6 +511,69 @@ jobs:
 #            fi
 #          done
 
+  # Just for test
+  map-global-uuid:
+    name: map-global-uuid
+    needs: checkout-and-build
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+        
+      # Checkout submodules
+      # Note: Uses 8 jobs for checking out submodules quicker
+      - name: Checkout submodules
+        shell: bash
+        run: |
+          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
+          git config --global url."https://github.com/".insteadOf "git@github.com:"
+          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
+          git submodule sync --recursive
+          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1 --recursive --jobs 8
+          
+      - name: Download submodule_name artifact
+        uses: actions/download-artifact@v1
+        with:
+          name: submodule_name
+      
+      - name: Set SUBMODULE_NAME env var
+        run: |
+          SUB_NAME=$(cat submodule_name/submodule_name.txt)
+
+          if [ -z "$SUB_NAME" ]; then
+            echo "Error: Could not determine submodule name from artifact"
+            exit 1
+          else
+            echo ::set-env name=SUBMODULE_NAME::$SUB_NAME
+            echo SUBMODULE_NAME: $SUB_NAME
+          fi
+
+      # TODO: Convert these steps to docker-based action
+      - name: Setup node
+        if: env.SUBMODULE_NAME != ''
+        uses: actions/setup-node@v1
+        with:
+          node-version: "10.x"
+
+      # Custom action to check for OSS files
+      - name: compile map-global-uuid
+        if: env.SUBMODULE_NAME != ''
+        run: |
+          cd ./.github/actions/map-global-uuid
+          npm install
+          npm run build && npm run pack
+      
+      - name: map-global-uuid
+        if: env.SUBMODULE_NAME != ''
+        uses: ./.github/actions/map-global-uuid
+        with:
+          # Array describing the files
+          submodule-name: ${{ env.SUBMODULE_NAME }}
+
   # Tasks - this should all be wrapped in an action if possible:
   #   Checkout repo and submodule
   #   Get UUID from globals.json, using SUBMOBULE_NAME as key
