feat: created individual jobs for validating catalog and uuid

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -95,7 +95,6 @@ jobs:
         with:
           name: submodule_name
           path: ./submodule_name.txt
-      
 
       - name: Setup node
         if: env.SUBMODULE_NAME != ''
@@ -103,19 +102,19 @@ jobs:
         with:
           node-version: "10.x"
 
-      # Custom action to check for OSS files
-      - name: compile-action
-        run: |
-          cd ./.github/actions/files-present-action
-          npm install
-          npm run build
-      
-      - name: files-present-action
-        uses: ./.github/actions/files-present-action
-        with:
-          # Array describing the files
-          path: ./${{ env.SUBMODULE_NAME }}
-          files: "README.md, .prettierrc.js, .eslintrc.js, .gitignore, package.json, LICENSE, THIRD_PARTY_NOTICES.md, CODE_OF_CONDUCT.md, cla.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, nr1.json, catalog/config.json"
+#      # Custom action to check for OSS files
+#      - name: compile-action
+#        run: |
+#          cd ./.github/actions/files-present-action
+#          npm install
+#          npm run build
+#      
+#      - name: files-present-action
+#        uses: ./.github/actions/files-present-action
+#        with:
+#          # Array describing the files
+#          path: ./${{ env.SUBMODULE_NAME }}
+#          files: "README.md, .prettierrc.js, .eslintrc.js, .gitignore, package.json, LICENSE, THIRD_PARTY_NOTICES.md, CODE_OF_CONDUCT.md, cla.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, nr1.json, icon.png, catalog/config.json"
 
       # Old method of checking for OSS files
 #      - name: Check for OSS Files
@@ -182,17 +181,17 @@ jobs:
 
       # Could be its own job that depends on `checkout and build` job?
       #   A: Only if we can pass submodule_name between jobs as artifact
-      - name: ESLinting
-        if: env.SUBMODULE_NAME != ''
-        working-directory: ./${{ env.SUBMODULE_NAME }}
-        run: npm run eslint-check
-
-      # Could be its own job that depends on `checkout and build` job?
-      #   A: Only if we can pass submodule_name between jobs as artifact
-      - name: Test Code
-        if: env.SUBMODULE_NAME != ''
-        working-directory: ./${{ env.SUBMODULE_NAME }}
-        run: npm test
+#      - name: ESLinting
+#        if: env.SUBMODULE_NAME != ''
+#        working-directory: ./${{ env.SUBMODULE_NAME }}
+#        run: npm run eslint-check
+#
+#      # Could be its own job that depends on `checkout and build` job?
+#      #   A: Only if we can pass submodule_name between jobs as artifact
+#      - name: Test Code
+#        if: env.SUBMODULE_NAME != ''
+#        working-directory: ./${{ env.SUBMODULE_NAME }}
+#        run: npm test
 
 #      # Validate Ability to publish code (Issue #2)
 #      # Requires API Key
@@ -210,28 +209,28 @@ jobs:
 
       # Could be its own job that depends on `checkout and build` job?
       #   A: Only if we can pass submodule_name between jobs as artifact
-      - name: Validate Catalog Data (#1)
-        if: env.SUBMODULE_NAME != ''
-        run: |
-          rootDir=./${{ env.SUBMODULE_NAME }}/
-          
-          declare -a files=(
-            nr1.json
-            icon.png
-            catalog/config.json
-          )
-          
-          for FILE in "${files[@]}"
-          do
-            if [ ! -f "${rootDir}$FILE" ]; then
-              printf "\n"
-              echo "Error: $FILE is missing from Nerdpack"
-              printf "\n"
-              exit 1
-            else
-              echo "Found "${rootDir}$FILE
-            fi
-          done
+#      - name: Validate Catalog Data (#1)
+#        if: env.SUBMODULE_NAME != ''
+#        run: |
+#          rootDir=./${{ env.SUBMODULE_NAME }}/
+#          
+#          declare -a files=(
+#            nr1.json
+#            icon.png
+#            catalog/config.json
+#          )
+#          
+#          for FILE in "${files[@]}"
+#          do
+#            if [ ! -f "${rootDir}$FILE" ]; then
+#              printf "\n"
+#              echo "Error: $FILE is missing from Nerdpack"
+#              printf "\n"
+#              exit 1
+#            else
+#              echo "Found "${rootDir}$FILE
+#            fi
+#          done
           
 #           TODO:
 #             # Validate package.json semantic versioning
@@ -355,6 +354,175 @@ jobs:
         if: env.SUBMODULE_NAME != ''
         working-directory: ./${{ env.SUBMODULE_NAME }}
         run: npm test
+  
+  validate-catalog-nerdpack:
+    name: validate-catalog-requirements
+    needs: checkout-and-build
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+        
+      # Checkout submodules
+      # Note: Uses 8 jobs for checking out submodules quicker
+      - name: Checkout submodules
+        shell: bash
+        run: |
+          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
+          git config --global url."https://github.com/".insteadOf "git@github.com:"
+          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
+          git submodule sync --recursive
+          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1 --recursive --jobs 8
+          
+      - name: Download submodule_name artifact
+        uses: actions/download-artifact@v1
+        with:
+          name: submodule_name
+      
+      - name: Set SUBMODULE_NAME env var
+        run: |
+          SUB_NAME=$(cat submodule_name/submodule_name.txt)
+
+          if [ -z "$SUB_NAME" ]; then
+            echo "Error: Could not determine submodule name from artifact"
+            exit 1
+          else
+            echo ::set-env name=SUBMODULE_NAME::$SUB_NAME
+            echo SUBMODULE_NAME: $SUB_NAME
+          fi
+
+      # TODO: Convert these steps to docker-based action
+      - name: Setup node
+        if: env.SUBMODULE_NAME != ''
+        uses: actions/setup-node@v1
+        with:
+          node-version: "10.x"
+
+      # Custom action to check for OSS files
+      - name: compile-action
+        if: env.SUBMODULE_NAME != ''
+        run: |
+          cd ./.github/actions/files-present-action
+          npm install
+          npm run build && npm run pack
+      
+      - name: files-present-action
+        if: env.SUBMODULE_NAME != ''
+        uses: ./.github/actions/files-present-action
+        with:
+          # Array describing the files
+          path: ./${{ env.SUBMODULE_NAME }}
+          files: "README.md, .prettierrc.js, .eslintrc.js, .gitignore, package.json, LICENSE, THIRD_PARTY_NOTICES.md, CODE_OF_CONDUCT.md, cla.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, nr1.json, icon.png, catalog/config.json"
+
+      # Old method of checking for OSS files
+#      - name: Check for OSS Files
+#        if: env.SUBMODULE_NAME != ''
+#        run: |
+#          rootDir=./${{ env.SUBMODULE_NAME }}/
+#          
+#          ls -la $rootDir
+#          ls -la $rootDir/.github
+#          
+#          if [ -d "${rootDir}/.github" ]; then
+#            ls -la $rootDir/.github
+#          else
+#            echo ".github directory not found"
+#          fi
+#          
+#          if [ -d "${rootDir}/.github/ISSUE_TEMPLATE" ]; then
+#            ls -la $rootDir/.github/ISSUE_TEMPLATE
+#          else
+#            echo "ISSUE_TEMPLATE directory not found"
+#          fi
+#          
+#          declare -a files=(
+#            "README.md"
+#            ".prettierrc.js"
+#            ".eslintrc.js"
+#            ".gitignore"
+#            "package.json"
+#            "LICENSE"
+#            "THIRD_PARTY_NOTICES.md"
+#            "CODE_OF_CONDUCT.md"
+#            "cla.md"
+#            ".github/ISSUE_TEMPLATE/bug_report.md"
+#            ".github/ISSUE_TEMPLATE/enhancement.md"
+#            nr1.json
+#            catalog/config.json
+#          )
+#          
+#          for FILE in "${files[@]}"
+#          do
+#            if [ ! -f "${rootDir}$FILE" ]; then
+#              printf "\n"
+#              echo "Error: $FILE is missing from Nerdpack"
+#              printf "\n"
+#              exit 1
+#            else
+#              echo "Found "${rootDir}$FILE
+#            fi
+#          done
+
+  # Tasks - this should all be wrapped in an action if possible:
+  #   Checkout repo and submodule
+  #   Get UUID from globals.json, using SUBMOBULE_NAME as key
+  #   if it doesn't exist
+  #     call nr1 nerdpack:uuid -gf
+  #     copy uuid value from nr1.json INTO globals.json
+  #     commit SUBMODULE_NAME/nr1.json AND globals.json
+  #     TODO: evaluate if this is all we should do, as I'm unsure if the CI tooling can commit to a PR branch from a fork without permission.
+  #     TODO: Copying the UUID into nr1.json could possibly happen on merge 
+  #   else
+  #     copy value from globals.json into nr1.json
+  #     - commit updated nr1.json to submodule repo
+  #     - possibly call git submodule update remote (to update the SHA we are using for the submodule?)
+  #     - finally, commit the updated submodule SHA commit value to the PR branch (this effectively completes the update of the nr1.json with the correct UUID)
+  validate-catalog-uuid:
+    name: test
+    needs: checkout-and-build
+    if: github.event_name != 'pull_request'  
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+        
+      # Checkout submodules
+      # Note: Uses 8 jobs for checking out submodules quicker
+      - name: Checkout submodules
+        shell: bash
+        run: |
+          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
+          git config --global url."https://github.com/".insteadOf "git@github.com:"
+          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
+          git submodule sync --recursive
+          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1 --recursive --jobs 8
+          
+      - name: Download submodule_name artifact
+        uses: actions/download-artifact@v1
+        with:
+          name: submodule_name
+      
+      - name: Set SUBMODULE_NAME env var
+        run: |
+          SUB_NAME=$(cat submodule_name/submodule_name.txt)
+
+          if [ -z "$SUB_NAME" ]; then
+            echo "Error: Could not determine submodule name from artifact"
+            exit 1
+          else
+            echo ::set-env name=SUBMODULE_NAME::$SUB_NAME
+            echo SUBMODULE_NAME: $SUB_NAME
+          fi
+
+      # TODO: Create action to handle finding and creating/updating UUID
+
 
   publish: 
     name: Publish Nerdpack
