fix: adding some debugging

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -482,10 +482,20 @@ jobs:
       - name: Check and Commit globals.json
         if: steps.uuid.outputs.globals-updated == 'true'
         run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          echo "globals.json was changed -- committing"
-          git commit globals.json "Add new UUID for submodule: ${{ env.SUBMODULE_NAME }}"
+          echo "Current directory:"
+          pwd
+          ls -la
+
+          if [ -f "globals.json" ]; then
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            echo "globals.json was changed -- committing"
+            git commit ./globals.json "Add new UUID for submodule: ${{ env.SUBMODULE_NAME }}"
+          else
+            echo "Cannot find globals.json"
+            exit 1
+          fi
+
       - name: Push Commit
         if: steps.uuid.outputs.globals-updated == 'true'
         uses: ad-m/github-push-action@v0.5.0
